name: Slide CLI Testing
on:
  push:
    tags-ignore:
      - "*"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: 
          - 1.24
          - 1.25

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: |
          go build -v 

      - name: Lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go vet -composites=false ./...
          staticcheck ./...

      - name: Run tests
        run: |
          go test -v ./...